// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// build_lookup_rcpp
List build_lookup_rcpp(List dense_leaf_ids, List native_leaf_ids, SEXP extr_idx_sexp, SEXP bg_idx_sexp, bool all);
RcppExport SEXP _boosted_build_lookup_rcpp(SEXP dense_leaf_idsSEXP, SEXP native_leaf_idsSEXP, SEXP extr_idx_sexpSEXP, SEXP bg_idx_sexpSEXP, SEXP allSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type dense_leaf_ids(dense_leaf_idsSEXP);
    Rcpp::traits::input_parameter< List >::type native_leaf_ids(native_leaf_idsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type extr_idx_sexp(extr_idx_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type bg_idx_sexp(bg_idx_sexpSEXP);
    Rcpp::traits::input_parameter< bool >::type all(allSEXP);
    rcpp_result_gen = Rcpp::wrap(build_lookup_rcpp(dense_leaf_ids, native_leaf_ids, extr_idx_sexp, bg_idx_sexp, all));
    return rcpp_result_gen;
END_RCPP
}
// stack_leaf_counts_rcpp
NumericVector stack_leaf_counts_rcpp(List dense_leaf_ids, IntegerVector n_leaves, IntegerVector idx, IntegerVector tree_idx);
RcppExport SEXP _boosted_stack_leaf_counts_rcpp(SEXP dense_leaf_idsSEXP, SEXP n_leavesSEXP, SEXP idxSEXP, SEXP tree_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type dense_leaf_ids(dense_leaf_idsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n_leaves(n_leavesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type tree_idx(tree_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(stack_leaf_counts_rcpp(dense_leaf_ids, n_leaves, idx, tree_idx));
    return rcpp_result_gen;
END_RCPP
}
// stack_leaf_masses_rcpp
NumericVector stack_leaf_masses_rcpp(List dense_leaf_ids, IntegerVector n_leaves, IntegerVector idx, NumericVector weights, IntegerVector tree_idx);
RcppExport SEXP _boosted_stack_leaf_masses_rcpp(SEXP dense_leaf_idsSEXP, SEXP n_leavesSEXP, SEXP idxSEXP, SEXP weightsSEXP, SEXP tree_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type dense_leaf_ids(dense_leaf_idsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n_leaves(n_leavesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type tree_idx(tree_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(stack_leaf_masses_rcpp(dense_leaf_ids, n_leaves, idx, weights, tree_idx));
    return rcpp_result_gen;
END_RCPP
}
// leaf_llrs_rcpp
List leaf_llrs_rcpp(NumericVector ce_all, NumericVector cb_all, IntegerVector n_leaves, IntegerVector tree_idx, double N_E, double N_B, double alpha);
RcppExport SEXP _boosted_leaf_llrs_rcpp(SEXP ce_allSEXP, SEXP cb_allSEXP, SEXP n_leavesSEXP, SEXP tree_idxSEXP, SEXP N_ESEXP, SEXP N_BSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type ce_all(ce_allSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cb_all(cb_allSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n_leaves(n_leavesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type tree_idx(tree_idxSEXP);
    Rcpp::traits::input_parameter< double >::type N_E(N_ESEXP);
    Rcpp::traits::input_parameter< double >::type N_B(N_BSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(leaf_llrs_rcpp(ce_all, cb_all, n_leaves, tree_idx, N_E, N_B, alpha));
    return rcpp_result_gen;
END_RCPP
}
// score_snps_rcpp
SEXP score_snps_rcpp(SEXP test_leaf_map, SEXP leaf_llrs_by_tree, int Tm, int n);
RcppExport SEXP _boosted_score_snps_rcpp(SEXP test_leaf_mapSEXP, SEXP leaf_llrs_by_treeSEXP, SEXP TmSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type test_leaf_map(test_leaf_mapSEXP);
    Rcpp::traits::input_parameter< SEXP >::type leaf_llrs_by_tree(leaf_llrs_by_treeSEXP);
    Rcpp::traits::input_parameter< int >::type Tm(TmSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(score_snps_rcpp(test_leaf_map, leaf_llrs_by_tree, Tm, n));
    return rcpp_result_gen;
END_RCPP
}
// snp_lookup_rcpp
SEXP snp_lookup_rcpp(DataFrame pairs, SEXP snps_ext_by_leaf, SEXP snps_bg_by_leaf, SEXP snps_all_by_leaf);
RcppExport SEXP _boosted_snp_lookup_rcpp(SEXP pairsSEXP, SEXP snps_ext_by_leafSEXP, SEXP snps_bg_by_leafSEXP, SEXP snps_all_by_leafSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type pairs(pairsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type snps_ext_by_leaf(snps_ext_by_leafSEXP);
    Rcpp::traits::input_parameter< SEXP >::type snps_bg_by_leaf(snps_bg_by_leafSEXP);
    Rcpp::traits::input_parameter< SEXP >::type snps_all_by_leaf(snps_all_by_leafSEXP);
    rcpp_result_gen = Rcpp::wrap(snp_lookup_rcpp(pairs, snps_ext_by_leaf, snps_bg_by_leaf, snps_all_by_leaf));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_boosted_build_lookup_rcpp", (DL_FUNC) &_boosted_build_lookup_rcpp, 5},
    {"_boosted_stack_leaf_counts_rcpp", (DL_FUNC) &_boosted_stack_leaf_counts_rcpp, 4},
    {"_boosted_stack_leaf_masses_rcpp", (DL_FUNC) &_boosted_stack_leaf_masses_rcpp, 5},
    {"_boosted_leaf_llrs_rcpp", (DL_FUNC) &_boosted_leaf_llrs_rcpp, 7},
    {"_boosted_score_snps_rcpp", (DL_FUNC) &_boosted_score_snps_rcpp, 4},
    {"_boosted_snp_lookup_rcpp", (DL_FUNC) &_boosted_snp_lookup_rcpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_boosted(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
