// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// score_snps_rcpp
SEXP score_snps_rcpp(SEXP test_leaf_map, SEXP leaf_llrs_by_tree, int Tm, int n);
RcppExport SEXP _boosted_score_snps_rcpp(SEXP test_leaf_mapSEXP, SEXP leaf_llrs_by_treeSEXP, SEXP TmSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type test_leaf_map(test_leaf_mapSEXP);
    Rcpp::traits::input_parameter< SEXP >::type leaf_llrs_by_tree(leaf_llrs_by_treeSEXP);
    Rcpp::traits::input_parameter< int >::type Tm(TmSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(score_snps_rcpp(test_leaf_map, leaf_llrs_by_tree, Tm, n));
    return rcpp_result_gen;
END_RCPP
}
// snp_lookup_rcpp
SEXP snp_lookup_rcpp(DataFrame pairs, List snps_ext_by_leaf, List snps_bg_by_leaf, SEXP snps_all_by_leaf);
RcppExport SEXP _boosted_snp_lookup_rcpp(SEXP pairsSEXP, SEXP snps_ext_by_leafSEXP, SEXP snps_bg_by_leafSEXP, SEXP snps_all_by_leafSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type pairs(pairsSEXP);
    Rcpp::traits::input_parameter< List >::type snps_ext_by_leaf(snps_ext_by_leafSEXP);
    Rcpp::traits::input_parameter< List >::type snps_bg_by_leaf(snps_bg_by_leafSEXP);
    Rcpp::traits::input_parameter< SEXP >::type snps_all_by_leaf(snps_all_by_leafSEXP);
    rcpp_result_gen = Rcpp::wrap(snp_lookup_rcpp(pairs, snps_ext_by_leaf, snps_bg_by_leaf, snps_all_by_leaf));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_boosted_score_snps_rcpp", (DL_FUNC) &_boosted_score_snps_rcpp, 4},
    {"_boosted_snp_lookup_rcpp", (DL_FUNC) &_boosted_snp_lookup_rcpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_boosted(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
