# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.build_lookup_rcpp <- function(dense_leaf_ids, native_leaf_ids, extr_idx, bg_idx, all = FALSE) {
    .Call(`_boosted_build_lookup_rcpp`, dense_leaf_ids, native_leaf_ids, extr_idx, bg_idx, all)
}

.score_snps_rcpp <- function(test_leaf_map, leaf_llrs_by_tree, Tm, n) {
    .Call(`_boosted_score_snps_rcpp`, test_leaf_map, leaf_llrs_by_tree, Tm, n)
}

.snp_lookup_rcpp <- function(pairs, snps_ext_by_leaf, snps_bg_by_leaf, snps_all_by_leaf = NULL) {
    .Call(`_boosted_snp_lookup_rcpp`, pairs, snps_ext_by_leaf, snps_bg_by_leaf, snps_all_by_leaf)
}

