# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.build_lookup_rcpp <- function(dense_leaf_ids, native_leaf_ids, extr_idx_sexp = NULL, bg_idx_sexp = NULL, all = FALSE) {
    .Call(`_boosted_build_lookup_rcpp`, dense_leaf_ids, native_leaf_ids, extr_idx_sexp, bg_idx_sexp, all)
}

.stack_leaf_counts_rcpp <- function(dense_leaf_ids, n_leaves, idx, tree_idx) {
    .Call(`_boosted_stack_leaf_counts_rcpp`, dense_leaf_ids, n_leaves, idx, tree_idx)
}

.stack_leaf_masses_rcpp <- function(dense_leaf_ids, n_leaves, idx, weights, tree_idx) {
    .Call(`_boosted_stack_leaf_masses_rcpp`, dense_leaf_ids, n_leaves, idx, weights, tree_idx)
}

.leaf_llrs_rcpp <- function(ce_all, cb_all, n_leaves, tree_idx, N_E, N_B, alpha = 0.5) {
    .Call(`_boosted_leaf_llrs_rcpp`, ce_all, cb_all, n_leaves, tree_idx, N_E, N_B, alpha)
}

.score_snps_rcpp <- function(test_leaf_map, leaf_llrs_by_tree, Tm, n) {
    .Call(`_boosted_score_snps_rcpp`, test_leaf_map, leaf_llrs_by_tree, Tm, n)
}

.snp_lookup_rcpp <- function(pairs, snps_ext_by_leaf = NULL, snps_bg_by_leaf = NULL, snps_all_by_leaf = NULL) {
    .Call(`_boosted_snp_lookup_rcpp`, pairs, snps_ext_by_leaf, snps_bg_by_leaf, snps_all_by_leaf)
}

